### ISSUE TITLE
Fork rollup-plugin-dev Plugin and Update to Remove Deprecated Dependencies

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#15]
# Description

[rollup-plugin-dev](https://github.com/pearofducks/rollup-plugin-dev/tree/master) uses a deprecated dependency. It hasn't been updated in a couple years, so I doubt it will be updated anytime in the near future. I want to fork the repository, update the dependencies, resolve any issues, and deploy the update to npm so I can use the updated dependency in this and future projects.

# Tasks

- [ ] fork the repository
- [ ] update the dependencies
- [ ] test the changes
- [ ] deploy the new plugin to npm
- [ ] update the dependency in this project

**Comment by azurepolarbear** [comment]
This issue will not be worked on.
