### ISSUE TITLE
Create Basic Color Classes

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#22]
# Description

Create the initial classes for the color scheme creation in generative art projects.

# Tasks

- [ ] Color class
- [ ] Color builder
- [ ] ColorGroup class
- [ ] Implement color transitions in both directions
  - [ ] Transparency Transition
  - [ ] Lerp Transition

**Comment by blwatkins** [comment]
# Current Tasks for Closing

- [ ] Complete MutedChristmas Collection Colors
- [ ] Create Second Collection
- [ ] get selected or random collection from collection factory -> return collection or factory
- [ ] build and test 1 rgb range factory
- [ ] build and test 1 hsb range factory
- [ ] RangeFactory -> get selected or random range color factory
- [ ] color factory builder -> factory type, collection/range selection, or random
- [ ] make sketch using color factory builder

# Notes about Color Schemes

Choices for color scheme
- how many groups?
- for each group
  - what kind of group is it?
  - if fixed
    - what kind of color factory?
    - if color collection
      which collection?
    - if range
      - which range?
      - RGB or HSB?
    - how many colors?
    - are the colors selected in order or randomly?
