### ISSUE TITLE
Configure CodeQL to Run on All Branches

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#28]
# Description

We want to configure CodeQL so we get a valid pass or fail when branches are scanned during pull requests.

# Tasks

- [x] Create proper repository file for CodeQL Settings
- [x] Test CodeQL Scanning results in `main` branch
- [x] Test CodeQL Scanning results in pull request

**Comment by blwatkins** [comment]
One more check to complete before this issue can be closed.

**Comment by blwatkins** [comment]
Confirmed code scans now working in pull requests.
