### ISSUE TITLE
Complete Color Unit Tests

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#33]
# Description

Complete the unit tests for the Color class (`./tests/common/color/color.test.ts`).

# Tasks

- [x] color built with (r,g,b,a) parameter
- [x] color built with (h,s,b) color
- [x] color built with (h,s,b,a) color
- [x] color built with (c) parameter
- [x] color built with (c,a) parameter
- [x] color set with (r,g,b) color
- [x] color set with (r,g,b,a) color
- [x] color set with (h,s,b) color
- [x] color set with (h,s,b,a) color
- [x] color set with (c) parameter
- [x] color set with (c,a) parameter
- [x] set red to value > 255
- [x] set red to value < 0
- [x] set green to value > 255
- [x] set green to value < 0
- [x] set blue to value > 255
- [x] set blue to value < 0
- [x] set alpha to value > 255
- [x] set alpha to value < 0
