### ISSUE TITLE
Move npm Scripts into Shell Script Files

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#34]
# Description

Some of the scripts in `package.json` are a little long. It would be better to have each one in its own shell file (script-name.sh)

# Tasks

- [ ] create `scripts` directory
- [ ] write shell script for each package.json script
  - [ ] lint-tests
  - [ ] build-and-test
  - [ ] test
  - [ ] build
  - [ ] dev
- [ ] update `package.json` to call the shell scripts when the commands are made

**Comment by azurepolarbear** [comment]
OBE
