### ISSUE TITLE
Make Template Deployable as an NPM Package

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#35]
# Description

I think it would be much easier to keep all projects up to date if the 'template' was deployed as a framework to [npm](https://www.npmjs.com/).

# Tasks

- [x] research deploying typescript to npm
- [x] choose one of the following
  - change repository name to something appropriate for the framework
  - fork template repository with a name appropriate for the framework
  - [x] create a new repository with a name appropriate for the framework
- [x] properly format the project so it is deployable, runnable, and testable
- [x] deploy to npm
- [x] test importing package into a new project repository

**Comment by azurepolarbear** [comment]
Generative library successfully published to npm

[@batpb/genart](https://www.npmjs.com/package/@batpb/genart)
