### ISSUE TITLE
Replace rollup-plugin-dev with @rollup/plugin-run

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#44]
# Description

There are vulnerabilities in rollup-plugin-dev. Until we can fork the repository and make the necessary updates (see #15), we should use [@rollup/plugin-run](https://github.com/rollup/plugins/tree/master/packages/run) for local development.

# Tasks

- [x] uninstall rollup-plugin-dev
- [x] install @rollup/plugin-run
- [x] configure @rollup/plugin-run
- [x] test locally

**Comment by azurepolarbear** [comment]
Changes for update completed.

@rollup/plugin-run was the wrong plugin. We needed rollup-plugin-serve.
