### ISSUE TITLE
Implement Node Resolution without the @rollup/plugin-node-resolve Plugin

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-project-template#9]
# Description

I think that [@rollup/plugin-node-resolve](https://github.com/rollup/plugins/tree/master/packages/node-resolve) is causing the build issues with the most recent versions of [rollup](https://github.com/rollup/rollup) (v4.4+).

When we have time, I'd like to see if it's possible to implement the node resolution algorithm being used by the plugin.

# Tasks

- [ ] research node resolution algorithm used by the plugin
- [ ] determine if it's possible to implement it ourselves
- [ ] update tasks to include implementation work

**Comment by blwatkins** [comment]
Build issues seem to have been resolved in v4.8.0 of Rollup. This change is not needed for now.
